### ISSUE TITLE
Prevent task generation for Playoff match winner before that match is On Field

### ISSUE THREAD

**Issue by FirstNight1** [FRC-Queue/FRC-Queue#1]
In the demo event at least, once Playoffs start, I can enter the winners for any Playoff match, regardless of that match's queueing status.  They may be queueing soon and I still get the task to enter a winner.

![image](https://user-images.githubusercontent.com/32118180/220823510-c9005bb2-3cf7-4e7d-962b-6361d32780d9.png)
![image](https://user-images.githubusercontent.com/32118180/220823527-5d4d8c9d-2162-4704-a27d-0a9315ce1ab5.png)

I'd suggest leaving the ability to edit all playoff matches in the bracket on the Playoff page, that way if something goes wrong or for whatever reason you can still update the winners there ahead of the queueing status.  But for the tasks, I don't think a task should be presented to assign a winner for a match until that match is on field.

**Comment by eforbes** [comment]
Thanks for the feedback- I agree the task does not need to be shown before the match is on field.

It's too late for this change to make it in for the 2023 season, but I'll keep track of it for a future update.

**Comment by eforbes** [comment]
A fix for this has been implemented. Thanks again for the feedback!
