### ISSUE TITLE
UI issues after permission changes

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#10]
I was assigned as a queuer in FRC Queue for an event and then made a manager. Without refreshing the page, I was granted the new permissions. However, there were some funky things with the UI (see screenshots).

![image](https://user-images.githubusercontent.com/22439365/229376349-6e68042f-83e8-4182-bbad-38396bb26777.png)
![image](https://user-images.githubusercontent.com/22439365/229376354-704beedf-64b5-4b6c-b24d-b00f97c7682f.png)

When I refreshed the page (trying to fix the UI), I was signed out of the application. After signing back in, this was resolved. Perhaps permission changes are uncommon enough that this isn't worth fixing, but thought I'd report it.

**Comment by eforbes** [comment]
A fix for this has been implemented. Thanks again for the feedback!
