### ISSUE TITLE
Multiple admins during playoffs

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#11]
During playoffs, the "who won?" questions don't seem to work properly across multiple users. One event admin was diligently selecting who won after each match, and the other event admin was still stuck on the "who won playoff 1?" question.

If the admin who was selecting who won wanted to switch this responsibility to another user, I'm not sure what they're supposed to do in this case.

![image](https://user-images.githubusercontent.com/22439365/229376465-c69d39c8-c5fa-43ee-9b9f-ca7b6944db01.png)

**Comment by eforbes** [comment]
A fix for this has been implemented. Thanks again for the feedback!
