### ISSUE TITLE
Create more specific error messages

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#12]
If a user has access to some but not all parts of FRC Queue for an event, the message says:

> Something went wrong. {email} does not have access to {event code}.

However {email} may have access to queue for {event code} but not to view /alliances or /fta or some other part of the system.

To help queuers at events debug, it might be helpful to say:

> Something went wrong. {email} does not have access to {module} for {event code}.

![image](https://user-images.githubusercontent.com/22439365/229376664-af3507df-ae81-4add-9b38-1f8ca9f1f36e.png)

**Comment by eforbes** [comment]
A fix for this has been implemented. Thanks again for the feedback!

Particularly for authorization errors- users are now presented with a request form that allows them to directly request the role they need to view the page or perform the action
