### ISSUE TITLE
International Phone Numbers are not Accepted in the System

### ISSUE THREAD

**Issue by KokoEd191** [FRC-Queue/FRC-Queue#2]
At the South Florida Regional I tried to input the phone number of FRC 8581 from Panama. The system rejected their phone number. Fortunately another volunteer gave up her phone so they could use FRC Queue. FRC 7403 was able to use the app due to having a phone with an American phone number. If we intended to use FRC Queue at the Championship (which I thin would best benefit international teams) we need to fix this issue.

**Comment by eforbes** [comment]
Thanks for the report- international phone numbers should already be supported but it is not clear in the UI what format to use.

I should be able to improve this- hopefully before week 2.

**Comment by KokoEd191** [comment]
I have a team from Turkey and from Canada at my week two. I’ll let you know how it goes.


Sent from Yahoo Mail for iPhone


On Sunday, March 5, 2023, 11:17 PM, Evan Forbes ***@***.***> wrote:




Thanks for the report- international phone numbers should already be supported but it is not clear in the UI what format to use.

I should be able to improve this- hopefully before week 2.

**Comment by eforbes** [comment]
This fix is now live:

![phone number country](https://user-images.githubusercontent.com/2548822/223203721-e45bbb77-41e0-4a36-ad15-8a4b36937561.png)
