### ISSUE TITLE
Close events which don't finish queueing

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#3]
In the event that a Lead Queuer stops interfacing with the system during finals (as I think is to be expected), the page continues to show "queueing soon" for the remaining matches.

For example, 2023CAOC, LQ marked F1 and then stopped interacting for F2 and F3. The result is this screen still showing 24 hours+ later:
![image](https://user-images.githubusercontent.com/22439365/224890668-a19658cc-65e0-46a7-af7a-31f4b20e574a.png)

When signed in, the system says "Expected now" and starts counting up from 0:00. If I refresh, it seems to start over with counting. 

I think given that some LQs are likely to forget to mark F2/F3 as on field, it would be nice if after a certain amount of time elapses (an hour? three hours?) from the event scheduled end time, we see this screen instead:
![image](https://user-images.githubusercontent.com/22439365/224890848-ed77b7b3-bc5c-46fa-9bce-0f8d64277a3d.png)

**Comment by eforbes** [comment]
A fix for this has been implemented. Thanks for the feedback!
