### ISSUE TITLE
Show past events under "Your events"

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#4]
From the queuer dashboard, the "Your events" section does not include past events. It would be nice to see them there to be able to easily access reports after the event is over. Also, in the case of issue #3, this would allow an LQ to properly close an event.
![image](https://user-images.githubusercontent.com/22439365/224891225-4ac97436-c93c-47db-b7c2-c7fd66fed382.png)

The admin page can still be accessed directly by URL, but that might not be immediately obvious.

**Comment by eforbes** [comment]
Past events are automatically cleaned up (and access for all users is revoked). I'll keep in mind the use case of sharing data for past events.
