### ISSUE TITLE
Explanations for stats

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#5]
It would be helpful to have a tooltip that explains what the "Avg queue latency" is calculating (and probably the other stats, for consistency). I can't totally tell looking at the data if the latency number is calculating the delay of the team to arrive (lateness of teams),  the amount of extra time teams spent in queue, or something else.

![image](https://user-images.githubusercontent.com/22439365/224891919-46600984-1df3-4e42-9fdb-b15a024e18fe.png)

**Comment by eforbes** [comment]
Stats pages have been removed for now. If I re-implement them I will keep this in mind to ensure they are actually useful
