### ISSUE TITLE
Cycle times funky for first three matches

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#6]
I think some of this is to be expected, but the cycle times for the first three matches of a day or after a break are funky. It might be worth hiding them. See below for an example:
![image](https://user-images.githubusercontent.com/22439365/224892273-fcafb885-fefc-4303-9659-5095f2205447.png)
In this case, the cycle time for QM1 should be 0 or null since it's the first qual of the day. I don't think it makes sense to calculate it from the final practice match.

QM2 shows as two seconds since QM1 and QM2 were queued at the same time for opening ceremonies. It seems like it's calculating based on queue time-->queue time cycle rather than on field-->on field cycle, which shouldn't have this 2s duration (unless I'm wrong and our LQ pressed on field for QM1 then QM2, which is possible).

The 48 minutes for QM3 is also wrong and seems like the cause is also calculating queue time-->queue time instead of on field-->on field.

**Comment by eforbes** [comment]
Stats pages have been removed for now. This data is already available to FTAs via FMS reports so isn't that useful
