### ISSUE TITLE
Add the ability to remove authorized queuers and managers

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#7]
Unless I'm missing something, I don't see the ability to remove queuers. In this case, there was a typo, so no big deal, but I could see a more time sensitive issue in the future.

![image](https://user-images.githubusercontent.com/22439365/226086538-ae315419-4b79-44ce-a348-e4f7fb999dfc.png)

**Comment by jaredhasenklein** [comment]
Also, if someone is a queuer and is made an admin, they appear in both lists. I'd think that they should upgrade/downgrade rather than appear in both (this isn't impacting functionality for someone who was a queuer and became a manager, but I could see the desire to demote someone from manager to queuer and being stuck).

**Comment by eforbes** [comment]
A fix for this has been implemented. Thanks again for the feedback!
