### ISSUE TITLE
Allow more granular permissions

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Queue/FRC-Queue#9]
The two sets of permissions (queuers and admins) are pretty extreme: ability to mark teams as arrived only or do everything.

In a perfect world, I think permissions should be toggleable per person (e.g. alliance selection on/off, adjust queue time on/off, etc.).

If that's too hard to implement, I think one or two additional levels of permissions could be helpful (maybe an intermediary "manager" role that can do most things the admins can, but not create users/delete the event/change major settings).

--

An example use case for this: at the San Diego regional, I was a regular queuer (not LQ) for a couple days and, because of the venue layout, I was checking in alliance reps rather than the LQ. The LQ needed to make me an admin so that I could use that part of the tool.

**Comment by eforbes** [comment]
I have updated the authorization system which I think should solve this issue. I haven't added a per-permission toggle yet but I think the expanded set of roles should help (and based on usage can be expanded even more)
